# Generated by Django 6.0.1 on 2026-03-04 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Hours of sleep, e.g. 7.5', max_digits=4, null=True)),
                ('sleep_quality', models.CharField(blank=True, help_text='Short description or rating of sleep quality', max_length=50)),
                ('exercise_type', models.CharField(blank=True, help_text='Type of exercise, e.g. walking, running', max_length=100)),
                ('exercise_duration', models.IntegerField(blank=True, help_text='Duration of exercise in minutes', null=True)),
                ('diet_notes', models.TextField(blank=True, help_text='Notes about meals or diet for the day')),
                ('mood_stress_level', models.CharField(blank=True, help_text="Mood/stress description, e.g. 'calm', 'stressed'", max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
